export const landingDocument = String.raw`<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="color-scheme" content="light">
    <meta name="description" content="Chatwright is the local-first runtime for conversational software.">
    <title>Chatwright — Test conversation software like a product</title>
    <style>
      :root { color-scheme: light; --ink:#111827; --soft:#566477; --line:#e5eaf0; --canvas:#fcfcfd; --blue:#2c6dcc; --mint:#50cba0; --mint-ink:#0d5e49; font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; }
      * { box-sizing:border-box; } html { scroll-behavior:smooth; } body { margin:0; color:var(--ink); background:var(--canvas); } a { color:inherit; }
      .wrap { width:min(1180px,calc(100% - 3rem)); margin-inline:auto; }
      .nav { position:sticky; z-index:10; top:0; border-bottom:1px solid rgba(229,234,240,.9); background:rgba(252,252,253,.9); backdrop-filter:blur(16px); }
      .nav > .wrap { min-height:72px; display:flex; align-items:center; justify-content:space-between; gap:1.2rem; }
      .brand { color:var(--ink); font-size:1.1rem; font-weight:730; letter-spacing:-.05em; text-decoration:none; } .brand small { margin-left:.45rem; color:var(--soft); font-size:.65rem; font-weight:650; letter-spacing:.02em; }
      .links { display:flex; align-items:center; gap:1.35rem; color:#4e5c70; font-size:.85rem; } .links a { text-decoration:none; } .links a:hover { color:var(--ink); }
      .button { min-height:2.7rem; display:inline-flex; align-items:center; justify-content:center; padding:0 .95rem; border:1px solid transparent; border-radius:.55rem; font:680 .84rem/1 inherit; text-decoration:none; transition:transform .18s ease,box-shadow .18s ease; } .button:hover { transform:translateY(-1px); }
      .primary { color:#06271d; background:var(--mint); box-shadow:0 8px 20px rgba(80,203,160,.17); } .quiet { border-color:var(--line); background:#fff; }
      .hero { display:grid; grid-template-columns:minmax(19rem,.82fr) minmax(32rem,1.18fr); align-items:center; gap:clamp(2.5rem,6vw,5.6rem); padding:clamp(5rem,9vw,8rem) 0 clamp(5.5rem,10vw,9rem); } .hero-intro { text-align:left; } .eyebrow { margin:0 0 1rem; color:var(--blue); font:700 .7rem/1.2 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; letter-spacing:.12em; text-transform:uppercase; }
      h1 { max-width:10ch; margin:0; font-size:clamp(3rem,5.25vw,5.15rem); line-height:.97; letter-spacing:-.078em; } .hero-copy { max-width:32rem; margin:1.4rem 0 0; color:var(--soft); font-size:clamp(1.02rem,1.35vw,1.17rem); line-height:1.6; }
      .actions { display:flex; justify-content:flex-start; flex-wrap:wrap; gap:.7rem; margin-top:1.75rem; } .proof { display:flex; justify-content:flex-start; flex-wrap:wrap; align-items:center; gap:.55rem 1rem; margin:1.25rem 0 0; color:#687588; font-size:.76rem; } .proof span::before { content:""; display:inline-block; width:.38rem; height:.38rem; margin:0 .36rem .06rem 0; border-radius:50%; background:var(--mint-ink); } .proof .offline { padding:.36rem .56rem; border:1px solid #bce9d8; border-radius:.42rem; color:var(--mint-ink); background:#effbf5; font-weight:800; box-shadow:0 5px 14px rgba(80,203,160,.13); } .proof .offline::before { margin-bottom:.03rem; }
      .hero-terminal { max-width:29rem; margin:1.65rem 0 0; } .hero-preview { min-width:0; } .preview-head { display:flex; align-items:end; justify-content:space-between; gap:1rem; margin:0 0 .85rem; } .preview-head h2 { margin:0; font-size:1rem; letter-spacing:-.025em; } .preview-head p { margin:.25rem 0 0; color:var(--soft); font-size:.83rem; } .preview-head .annotation { display:inline-block; padding-bottom:.35rem; background:url('/studio/annotations/not-a-marketing-screenshot-underline.png') center calc(100% + .35rem)/116% auto no-repeat; } .preview-head a { color:var(--mint-ink); font-size:.8rem; font-weight:700; text-decoration:none; }
      .browser { overflow:hidden; border:1px solid #dce3ea; border-radius:1rem; background:#101925; box-shadow:0 28px 70px rgba(29,43,60,.14); } .browser-bar { min-height:3.25rem; display:grid; grid-template-columns:minmax(0,1fr) auto; align-items:center; gap:.75rem; padding:.55rem .7rem .55rem 1rem; border-bottom:1px solid rgba(228,236,245,.13); background:#172231; }
      .address { min-width:0; overflow:hidden; padding:.48rem .7rem; border:1px solid rgba(228,236,245,.12); border-radius:.42rem; color:#d9e3ef; background:#101925; font:500 .69rem/1.1 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; text-decoration:none; text-overflow:ellipsis; white-space:nowrap; } .address:hover { color:#fff; border-color:rgba(140,227,184,.55); } .live { display:inline-flex; align-items:center; gap:.38rem; color:#8ce3b8; font:650 .67rem/1 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; } .live::before { content:""; width:.42rem; height:.42rem; border-radius:50%; background:currentColor; }
      iframe { display:block; width:100%; height:min(660px,53vw); min-height:500px; border:0; background:#101925; }
      .why { display:grid; grid-template-columns:minmax(0,1.05fr) minmax(19rem,.95fr); align-items:start; gap:clamp(2rem,7vw,7rem); padding:0 0 clamp(5.5rem,10vw,9rem); } .why h2 { max-width:8.5ch; margin:0; font-size:clamp(2.25rem,4.3vw,4.25rem); line-height:1; letter-spacing:-.065em; } .why-copy { display:grid; gap:1.25rem; } .why-copy > p { margin:0; color:var(--soft); font-size:1.03rem; line-height:1.65; }
      .steps { display:grid; margin-top:.35rem; border-top:1px solid var(--line); } .step { display:grid; grid-template-columns:2.4rem 1fr; gap:.8rem; padding:1.1rem 0; border-bottom:1px solid var(--line); } .step > span { color:var(--blue); font:650 .72rem/1.7 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; } .step strong { display:block; font-size:.95rem; } .step p { margin:.25rem 0 0; color:var(--soft); font-size:.84rem; line-height:1.5; }
      .cli { padding:clamp(2.2rem,5vw,4rem); border:1px solid var(--line); border-radius:.9rem; background:#f7f9fb; } .cli > p { margin:0 0 .65rem; color:var(--blue); font:700 .68rem/1.2 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; letter-spacing:.11em; text-transform:uppercase; } .cli h2 { max-width:640px; margin:0; font-size:clamp(1.8rem,3vw,2.75rem); line-height:1.04; letter-spacing:-.055em; } pre { overflow:auto; margin:1.7rem 0 0; padding:1.1rem 1.2rem; border-radius:.65rem; color:#d5e4ef; background:#101925; font:500 .76rem/1.8 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; } pre b { color:#8ce3b8; font-weight:inherit; }
      footer { padding:2.5rem 0 3rem; color:#718094; font-size:.78rem; } footer .wrap { display:flex; justify-content:space-between; gap:1rem; border-top:1px solid var(--line); padding-top:1.45rem; } footer a { color:var(--soft); text-decoration:none; }
      .fade { animation:fade .65s both cubic-bezier(.2,.8,.2,1); } .delay { animation-delay:.12s; } @keyframes fade { from { opacity:0; transform:translateY(14px); } to { opacity:1; transform:translateY(0); } } @media (prefers-reduced-motion:reduce) { *,*::before,*::after { animation-duration:.01ms!important; scroll-behavior:auto!important; transition-duration:.01ms!important; } }
      @media (max-width:960px) { .hero { grid-template-columns:1fr; text-align:center; } .hero-intro { text-align:center; } h1 { max-width:13ch; margin-inline:auto; } .hero-copy,.hero-terminal { margin-inline:auto; } .actions,.proof { justify-content:center; } }
      @media (max-width:720px) { .wrap { width:min(100% - 2rem,1180px); } .nav > .wrap { min-height:64px; } .links { display:none; } .brand small { display:none; } .hero { padding-top:4.6rem; } h1 { font-size:clamp(2.85rem,14vw,4.2rem); } .preview-head { align-items:start; flex-direction:column; } iframe { height:560px; min-height:0; } .why { grid-template-columns:1fr; } .why h2 { max-width:11ch; } footer .wrap { align-items:flex-start; flex-direction:column; } }
    </style>
  </head>
  <body>
    <header class="nav"><div class="wrap"><a class="brand" href="/" aria-label="Chatwright home">Chatwright <small>by sneat.dev</small></a><nav class="links" aria-label="Primary navigation"><a href="#live-lab">Emulators</a><a href="#how-it-works">How it works</a><a href="https://github.com/chatwright/cli">CLI</a><a href="https://sneat.dev/">sneat.dev</a></nav><a class="button primary" href="/studio/">Open Studio</a></div></header>
    <main>
      <section class="hero wrap"><div class="hero-intro"><p class="eyebrow fade">Chat-platform emulator · conversational testing runtime</p><h1 class="fade">Your bot has a user interface.<br>Test it like one.</h1><p class="hero-copy fade delay">Chatwright is a local-first chat-platform emulator—not automation of someone’s Telegram or WhatsApp client. Run your bot locally and keep every platform call as evidence, not a guess.</p><pre class="hero-terminal fade delay"><b>$</b> chatwright run onboarding.yaml --platform telegram
<b>✓</b> 4 assertions passed · 342 ms</pre><div class="actions fade delay"><a class="button primary" href="#live-lab">Try the emulator</a><a class="button quiet" href="https://github.com/chatwright/cli">Explore the CLI</a></div><p class="proof"><span class="offline">Works offline</span><span>Open-source CLI</span><span>Faithful Telegram &amp; WhatsApp emulators</span></p></div><section id="live-lab" class="hero-preview" aria-label="Interactive Studio preview"><div class="preview-head"><div><h2>Live chat-platform emulator</h2><p>It is the product, <span class="annotation">not a marketing screenshot</span>.</p></div><a href="/studio/">Open in a full tab →</a></div><div class="browser"><div class="browser-bar"><a class="address" href="/studio/" target="_blank" rel="noopener" aria-label="Open Chatwright Studio in a new tab">https://chatwright.dev/studio/</a><span class="live">live</span></div><iframe src="/studio/emulator" title="Chatwright live emulator" loading="eager"></iframe></div></section></section>
      <section id="how-it-works" class="why wrap"><h2>Every interaction stays explainable.</h2><div class="why-copy"><p>Chatwright drives a real conversation through emulated platform APIs, then correlates what a user saw with the exact webhook, API call and assertion behind it. Work locally—even offline—until you choose to share the evidence.</p><div class="steps"><article class="step"><span>01</span><div><strong>Script the intent</strong><p>Describe a conversation in platform-neutral terms, including what should appear and when.</p></div></article><article class="step"><span>02</span><div><strong>Exercise the platform</strong><p>Use faithful Telegram and WhatsApp emulators while your bot still talks over real HTTP.</p></div></article><article class="step"><span>03</span><div><strong>Inspect the evidence</strong><p>Trace a message from user action to rendered reply, payload, timing and final assertion.</p></div></article></div></div></section>
      <section class="cli wrap"><p>Developer friendly from CLI to CI</p><h2>Keep the runtime close to your code. Open the Studio when you want the whole conversation in view.</h2><pre><b>$</b> chatwright run scenarios/language-choice.yaml --platform telegram
<b>✓</b> 4 assertions passed · 342 ms · evidence captured
<b>$</b> chatwright studio open</pre></section>
    </main>
    <footer><div class="wrap"><span>© 2026 Chatwright · by sneat.dev</span><a href="https://sneat.dev/">Explore sneat.dev →</a></div></footer>
  </body>
</html>`;
